services:
  php:
    image: php:8.2-apache
    container_name: php8-2
    ports: 
      - 8000:80
    volumes:
      - .:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  
  mysql:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: aC84xthK82YV6c
      MYSQL_DATABASE: olindo55_arcadia
      MYSQL_USER: olindo55_zoo_adm
      MYSQL_PASSWORD: Z00_@dmin
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - .arcadia.sql:/arcadia.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root 
      PMA_PASSWORD: aC84xthK82YV6c
    ports:
      - 8899:80

