# Utilisation de l'image PHP avec Apache
FROM php:8.2-apache

# Mise à jour des paquets et installation des dépendances
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y libmcrypt-dev libpng-dev libjpeg-dev libfreetype6-dev \
    libzip-dev libicu-dev zlib1g-dev git unzip libcurl4-openssl-dev

# Installer les extensions PHP requises
RUN docker-php-ext-install mysqli pdo pdo_mysql zip intl

# Installer l'extension mongodb
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Activer mod_rewrite
RUN a2enmod rewrite
RUN service apache2 restart

# Installer Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier l'application
COPY . /var/www/html

# Définir les permissions pour éviter les problèmes d'accès
RUN chown -R www-data:www-data /var/www/html && chmod -R 775 /var/www/html

# Changer le répertoire de travail
WORKDIR /var/www/html

# Exposer le port
EXPOSE 80

# Lancer Apache
CMD ["apache2-foreground"]

# Installer les dépendances via Composer
RUN composer clear-cache
RUN composer install --no-interaction --optimize-autoloader
